main.o: main.cpp ej3.cpp
			g++ main.cpp ej3.cpp -o ej3
			g++ tester.cpp ej3.cpp -o tester
			g++ casosComplejidad.cpp -o casos
			g++ casosRandom.cpp -o random
clean:
	rm -f ej3
	rm -f tester
	rm -f casos
	rm -f random
